#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdevTakipApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="odevkontrol")]
	public partial class OdevDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTbOgrenciler(TbOgrenciler instance);
    partial void UpdateTbOgrenciler(TbOgrenciler instance);
    partial void DeleteTbOgrenciler(TbOgrenciler instance);
    #endregion
		
		public OdevDataContext() : 
				base(global::OdevTakipApp.Properties.Settings.Default.odevkontrolConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OdevDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OdevDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OdevDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OdevDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TbOgrenciler> TbOgrencilers
		{
			get
			{
				return this.GetTable<TbOgrenciler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ogrenciler")]
	public partial class TbOgrenciler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _No;
		
		private string _Ad;
		
		private string _Soyad;
		
		private System.Nullable<bool> _Cinsiyet;
		
		private string _OdevKonusu;
		
		private System.Nullable<bool> _TeslimEdildiMi;
		
		private System.Nullable<System.DateTime> _TeslimTarihi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNoChanging(int value);
    partial void OnNoChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnCinsiyetChanging(System.Nullable<bool> value);
    partial void OnCinsiyetChanged();
    partial void OnOdevKonusuChanging(string value);
    partial void OnOdevKonusuChanged();
    partial void OnTeslimEdildiMiChanging(System.Nullable<bool> value);
    partial void OnTeslimEdildiMiChanged();
    partial void OnTeslimTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnTeslimTarihiChanged();
    #endregion
		
		public TbOgrenciler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Int NOT NULL")]
		public int No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyet", DbType="Bit")]
		public System.Nullable<bool> Cinsiyet
		{
			get
			{
				return this._Cinsiyet;
			}
			set
			{
				if ((this._Cinsiyet != value))
				{
					this.OnCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._Cinsiyet = value;
					this.SendPropertyChanged("Cinsiyet");
					this.OnCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdevKonusu", DbType="NVarChar(100)")]
		public string OdevKonusu
		{
			get
			{
				return this._OdevKonusu;
			}
			set
			{
				if ((this._OdevKonusu != value))
				{
					this.OnOdevKonusuChanging(value);
					this.SendPropertyChanging();
					this._OdevKonusu = value;
					this.SendPropertyChanged("OdevKonusu");
					this.OnOdevKonusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeslimEdildiMi", DbType="Bit")]
		public System.Nullable<bool> TeslimEdildiMi
		{
			get
			{
				return this._TeslimEdildiMi;
			}
			set
			{
				if ((this._TeslimEdildiMi != value))
				{
					this.OnTeslimEdildiMiChanging(value);
					this.SendPropertyChanging();
					this._TeslimEdildiMi = value;
					this.SendPropertyChanged("TeslimEdildiMi");
					this.OnTeslimEdildiMiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeslimTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> TeslimTarihi
		{
			get
			{
				return this._TeslimTarihi;
			}
			set
			{
				if ((this._TeslimTarihi != value))
				{
					this.OnTeslimTarihiChanging(value);
					this.SendPropertyChanging();
					this._TeslimTarihi = value;
					this.SendPropertyChanged("TeslimTarihi");
					this.OnTeslimTarihiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
